# Generated by Django 3.1.4 on 2021-01-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='record',
        ),
        migrations.AddField(
            model_name='profile',
            name='pictures',
            field=models.ImageField(default=None, upload_to='images/users/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
