# Generated by Django 3.1 on 2020-10-27 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('slug', models.SlugField(blank=True, default=None, max_length=128, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EditHeadText', models.TextField(max_length=128, verbose_name='Заголовок запчастей')),
                ('EditDisText', models.TextField(verbose_name='Об запчастях')),
                ('EditImages', models.ImageField(upload_to='images/', verbose_name='Изображение для разных видом транспорта')),
            ],
            options={
                'verbose_name': 'Об запчастях',
                'verbose_name_plural': 'Об запчастях',
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='EditCenterText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WelcomeText', models.TextField(max_length=128, verbose_name='Гостьевой текст')),
                ('EditHeadText', models.TextField(max_length=128, verbose_name='Центральный текст')),
                ('EditCenterImage', models.ImageField(upload_to='images/', verbose_name='Главная центральная картинки')),
            ],
            options={
                'verbose_name': 'Центральный текст',
                'verbose_name_plural': 'Центральные текста',
                'db_table': 'views',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SliderImages', models.ImageField(upload_to='images/', verbose_name='Изображение слайдера')),
            ],
            options={
                'verbose_name': 'Изображение слайдера',
                'verbose_name_plural': 'Изображения слайдера',
                'db_table': 'slider',
            },
        ),
        migrations.CreateModel(
            name='VariousDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariousImage', models.ImageField(upload_to='images/', verbose_name='Различные детали')),
            ],
            options={
                'verbose_name': 'Различные детали',
                'verbose_name_plural': 'Различные детали',
                'db_table': 'various',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.TextField(max_length=128, verbose_name='Название продукта')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
            options={
                'verbose_name': 'Продукция',
                'verbose_name_plural': 'Продукция',
                'db_table': 'product',
            },
        ),
    ]
