# Generated by Django 3.1 on 2020-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Имя сотрудника')),
                ('position', models.CharField(blank=True, max_length=128, verbose_name='Должность сотрудника')),
                ('discription', models.CharField(blank=True, max_length=128, verbose_name='Описание сотрудника')),
                ('images', models.ImageField(upload_to='images/', verbose_name='Фотография сотрудника')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.DeleteModel(
            name='EditAboutText',
        ),
    ]
